<?php 
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('album', array( 
        'action'=>'add'));?>">Add new album</a></p>

<table class="table">
<tr>
	<th></th>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach($albums as $album) : ?>
<tr>
	<td><?php echo (isset($albumMeta[$album->id]))?sprintf('<img src="%s">', $albumMeta[$album->id]['image']):''?></td>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
<?php if (isset($albumMeta[$album->id])): ?>
	<?php foreach ($albumMeta[$album->id]['tracks'] as $track): ?>
		<tr class="track">
			<td></td>
			<td colspan="3"><?php echo $this->escapeHtml($track['title']); ?>
			<?php if ($track['soundcloud']): ?>
				<object height="18" width="100%"> <param name="movie" value="https://player.soundcloud.com/player.swf?url=<?php echo urlencode($track['soundcloud']['uri']) ?>&amp;auto_play=false&amp;player_type=tiny&amp;font=Arial&amp;color=ff5400"></param> <param name="allowscriptaccess" value="always"></param> <param name="wmode" value="transparent"></param><embed wmode="transparent" allowscriptaccess="always" height="18" src="https://player.soundcloud.com/player.swf?url=<?php echo urlencode($track['soundcloud']['uri']); ?>&amp;auto_play=false&amp;player_type=tiny&amp;font=Arial&amp;color=ff5400" type="application/x-shockwave-flash" width="100%"></embed> </object>   
			<?php endif; ?>
			</td>
		</tr>
	<?php endforeach; ?>
<?php endif;?>
<?php endforeach; ?>
</table>
