<?php 
$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p><a href="<?php echo $this->url('album', array( 
        'action'=>'add'));?>">Add new album</a></p>

<table class="table" id="album-table">
<tr>
	<th></th>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
</table>
<script type="text/javascript">
var albumIds = <?php echo json_encode($albums)?>;
$(document).ready(function() {
	$(albumIds).each(function(key, value) {
		$.get('/album/albuminfo?album=' + value, function(result) {
			$('#album-table').append(result);
		});
	});
});
</script>